# encoding: utf-8
module CountrySelect

  ISO_COUNTRIES_FOR_SELECT =  [
    ["Afghanistan", "afg"],
    ["Åland Islands", "ala"],
    ["Albania", "alb"],
    ["Algeria", "dza"],
    ["American Samoa", "asm"],
    ["Andorra", "and"],
    ["Angola", "ago"],
    ["Anguilla", "aia"],
    ["Antarctica", "ata"],
    ["Antigua and Barbuda", "atg"],
    ["Argentina", "arg"],
    ["Armenia", "arm"],
    ["Aruba", "abw"],
    ["Australia", "aus"],
    ["Austria", "aut"],
    ["Azerbaijan", "aze"],
    ["Bahamas", "bhs"],
    ["Bahrain", "bhr"],
    ["Bangladesh", "bgd"],
    ["Barbados", "brb"],
    ["Belarus", "blr"],
    ["Belgium", "bel"],
    ["Belize", "blz"],
    ["Benin", "ben"],
    ["Bermuda", "bmu"],
    ["Bhutan", "btn"],
    ["Bolivia, Plurinational State of", "bol"],
    ["Bonaire, Sint Eustatius and Saba", "bes"],
    ["Bosnia and Herzegovina", "bih"],
    ["Botswana", "bwa"],
    ["Bouvet Island", "bvt"],
    ["Brazil", "bra"],
    ["British Indian Ocean Territory", "iot"],
    ["Brunei Darussalam", "brn"],
    ["Bulgaria", "bgr"],
    ["Burkina Faso", "bfa"],
    ["Burundi", "bdi"],
    ["Cambodia", "khm"],
    ["Cameroon", "cmr"],
    ["Canada", "can"],
    ["Cape Verde", "cpv"],
    ["Cayman Islands", "cym"],
    ["Central African Republic", "caf"],
    ["Chad", "tcd"],
    ["Chile", "chl"],
    ["China", "chn"],
    ["Christmas Island", "cxr"],
    ["Cocos (Keeling) Islands", "cck"],
    ["Colombia", "col"],
    ["Comoros", "com"],
    ["Congo", "cog"],
    ["Congo, the Democratic Republic of the", "cod"],
    ["Cook Islands", "cok"],
    ["Costa Rica", "cri"],
    ["Côte d'Ivoire", "civ"],
    ["Croatia", "hrv"],
    ["Cuba", "cub"],
    ["Curaçao", "cuw"],
    ["Cyprus", "cyp"],
    ["Czech Republic", "cze"],
    ["Denmark", "dnk"],
    ["Djibouti", "dji"],
    ["Dominica", "dma"],
    ["Dominican Republic", "dom"],
    ["Ecuador", "ecu"],
    ["Egypt", "egy"],
    ["El Salvador", "slv"],
    ["Equatorial Guinea", "gnq"],
    ["Eritrea", "eri"],
    ["Estonia", "est"],
    ["Ethiopia", "eth"],
    ["Falkland Islands (Malvinas)", "flk"],
    ["Faroe Islands", "fro"],
    ["Fiji", "fji"],
    ["Finland", "fin"],
    ["France", "fra"],
    ["French Guiana", "guf"],
    ["French Polynesia", "pyf"],
    ["French Southern Territories", "atf"],
    ["Gabon", "gab"],
    ["Gambia", "gmb"],
    ["Georgia", "geo"],
    ["Germany", "deu"],
    ["Ghana", "gha"],
    ["Gibraltar", "gib"],
    ["Greece", "grc"],
    ["Greenland", "grl"],
    ["Grenada", "grd"],
    ["Guadeloupe", "glp"],
    ["Guam", "gum"],
    ["Guatemala", "gtm"],
    ["Guernsey", "ggy"],
    ["Guinea", "gin"],
    ["Guinea-Bissau", "gnb"],
    ["Guyana", "guy"],
    ["Haiti", "hti"],
    ["Heard Island and McDonald Islands", "hmd"],
    ["Holy See (Vatican City State)", "vat"],
    ["Honduras", "hnd"],
    ["Hong Kong", "hkg"],
    ["Hungary", "hun"],
    ["Iceland", "isl"],
    ["India", "ind"],
    ["Indonesia", "idn"],
    ["Iran, Islamic Republic of", "irn"],
    ["Iraq", "irq"],
    ["Ireland", "irl"],
    ["Isle of Man", "imn"],
    ["Israel", "isr"],
    ["Italy", "ita"],
    ["Jamaica", "jam"],
    ["Japan", "jpn"],
    ["Jersey", "jey"],
    ["Jordan", "jor"],
    ["Kazakhstan", "kaz"],
    ["Kenya", "ken"],
    ["Kiribati", "kir"],
    ["Korea, Democratic People's Republic of", "prk"],
    ["Korea, Republic of", "kor"],
    ["Kuwait", "kwt"],
    ["Kyrgyzstan", "kgz"],
    ["Lao People's Democratic Republic", "lao"],
    ["Latvia", "lva"],
    ["Lebanon", "lbn"],
    ["Lesotho", "lso"],
    ["Liberia", "lbr"],
    ["Libya", "lby"],
    ["Liechtenstein", "lie"],
    ["Lithuania", "ltu"],
    ["Luxembourg", "lux"],
    ["Macao", "mac"],
    ["Macedonia, the former Yugoslav Republic of", "mkd"],
    ["Madagascar", "mdg"],
    ["Malawi", "mwi"],
    ["Malaysia", "mys"],
    ["Maldives", "mdv"],
    ["Mali", "mli"],
    ["Malta", "mlt"],
    ["Marshall Islands", "mhl"],
    ["Martinique", "mtq"],
    ["Mauritania", "mrt"],
    ["Mauritius", "mus"],
    ["Mayotte", "myt"],
    ["Mexico", "mex"],
    ["Micronesia, Federated States of", "fsm"],
    ["Moldova, Republic of", "mda"],
    ["Monaco", "mco"],
    ["Mongolia", "mng"],
    ["Montenegro", "mne"],
    ["Montserrat", "msr"],
    ["Morocco", "mar"],
    ["Mozambique", "moz"],
    ["Myanmar", "mmr"],
    ["Namibia", "nam"],
    ["Nauru", "nru"],
    ["Nepal", "npl"],
    ["Netherlands", "nld"],
    ["New Caledonia", "ncl"],
    ["New Zealand", "nzl"],
    ["Nicaragua", "nic"],
    ["Niger", "ner"],
    ["Nigeria", "nga"],
    ["Niue", "niu"],
    ["Norfolk Island", "nfk"],
    ["Northern Mariana Islands", "mnp"],
    ["Norway", "nor"],
    ["Oman", "omn"],
    ["Pakistan", "pak"],
    ["Palau", "plw"],
    ["Palestine, State of", "pse"],
    ["Panama", "pan"],
    ["Papua New Guinea", "png"],
    ["Paraguay", "pry"],
    ["Peru", "per"],
    ["Philippines", "phl"],
    ["Pitcairn", "pcn"],
    ["Poland", "pol"],
    ["Portugal", "prt"],
    ["Puerto Rico", "pri"],
    ["Qatar", "qat"],
    ["Réunion", "reu"],
    ["Romania", "rou"],
    ["Russian Federation", "rus"],
    ["Rwanda", "rwa"],
    ["Saint Barthélemy", "blm"],
    ["Saint Helena, Ascension and Tristan da Cunha", "shn"],
    ["Saint Kitts and Nevis", "kna"],
    ["Saint Lucia", "lca"],
    ["Saint Martin (French part)", "maf"],
    ["Saint Pierre and Miquelon", "spm"],
    ["Saint Vincent and the Grenadines", "vct"],
    ["Samoa", "wsm"],
    ["San Marino", "smr"],
    ["Sao Tome and Principe", "stp"],
    ["Saudi Arabia", "sau"],
    ["Senegal", "sen"],
    ["Serbia", "srb"],
    ["Seychelles", "syc"],
    ["Sierra Leone", "sle"],
    ["Singapore", "sgp"],
    ["Sint Maarten (Dutch part)", "sxm"],
    ["Slovakia", "svk"],
    ["Slovenia", "svn"],
    ["Solomon Islands", "slb"],
    ["Somalia", "som"],
    ["South Africa", "zaf"],
    ["South Georgia and the South Sandwich Islands", "sgs"],
    ["South Sudan", "ssd"],
    ["Spain", "esp"],
    ["Sri Lanka", "lka"],
    ["Sudan", "sdn"],
    ["Suriname", "sur"],
    ["Svalbard and Jan Mayen", "sjm"],
    ["Swaziland", "swz"],
    ["Sweden", "swe"],
    ["Switzerland", "che"],
    ["Syrian Arab Republic", "syr"],
    ["Taiwan, Province of China", "twn"],
    ["Tajikistan", "tjk"],
    ["Tanzania, United Republic of", "tza"],
    ["Thailand", "tha"],
    ["Timor-Leste", "tls"],
    ["Togo", "tgo"],
    ["Tokelau", "tkl"],
    ["Tonga", "ton"],
    ["Trinidad and Tobago", "tto"],
    ["Tunisia", "tun"],
    ["Turkey", "tur"],
    ["Turkmenistan", "tkm"],
    ["Turks and Caicos Islands", "tca"],
    ["Tuvalu", "tuv"],
    ["Uganda", "uga"],
    ["Ukraine", "ukr"],
    ["United Arab Emirates", "are"],
    ["United Kingdom", "gbr"],
    ["United States", "usa"],
    ["United States Minor Outlying Islands", "umi"],
    ["Uruguay", "ury"],
    ["Uzbekistan", "uzb"],
    ["Vanuatu", "vut"],
    ["Venezuela, Bolivarian Republic of", "ven"],
    ["Viet Nam", "vnm"],
    ["Virgin Islands, British", "vgb"],
    ["Virgin Islands, U.S.", "vir"],
    ["Wallis and Futuna", "wlf"],
    ["Western Sahara", "esh"],
    ["Yemen", "yem"],
    ["Zambia", "zmb"],
    ["Zimbabwe", "zwe"]
  ] unless const_defined?("ISO_COUNTRIES_FOR_SELECT")

  COUNTRIES = Hash[ISO_COUNTRIES_FOR_SELECT.flatten].invert unless const_defined?("COUNTRIES")
  COUNTRIES_FOR_SELECT = ISO_COUNTRIES_FOR_SELECT.map { |c|c[0] } unless const_defined?("COUNTRIES_FOR_SELECT")
end
