# encoding: utf-8
module CountrySelect

  ISO_COUNTRIES_FOR_SELECT =  [
    ["Djibouti", "DJI"],
    ["Trinidad and Tobago", "TTO"],
    ["Singapore", "SIN"],
    ["Australia", "AUS"],
    ["Japan", "JPN"],
    ["Afghanistan", "AFG"],
    ["Albania", "ALB"],
    ["Algeria", "ALG"],
    ["Andorra", "AND"],
    ["Angola", "ANG"],
    ["Antigua and Barbuda", "ANT"],
    ["Argentina", "ARG"],
    ["Armenia", "ARM"],
    ["Aruba", "ARU"],
    ["Austria", "AUT"],
    ["Azerbaidjan", "AZE"],
    ["Bahamas", "BAH"],
    ["Bahrain", "BRN"],
    ["Bangladesh", "BAN"],
    ["Barbados", "BAR"],
    ["Belarus", "BLR"],
    ["Belgium", "BEL"],
    ["Belize", "BIZ"],
    ["Bénin", "BEN"],
    ["Bermuda", "BER"],
    ["Bolivarian Republic of Venezuela", "VEN"],
    ["Bolivia", "BOL"],
    ["Bosnia-Herzegovnia", "BIH"],
    ["Botswana", "BOT"],
    ["Brazil", "BRA"],
    ["Brunei Darussalam", "BRU"],
    ["Bulgaria", "BUL"],
    ["Burkina Faso ", "BUR"],
    ["Burundi", "BDI"],
    ["Cameroon", "CMR"],
    ["Canada", "CAN"],
    ["Cayman Islands", "CAY"],
    ["Central African Republic", "CAF"],
    ["Chile", "CHI"],
    ["Chinese Taipei", "TPE"],
    ["Colombia", "COL"],
    ["Comores*", "COM"],
    ["Congo", "CGO"],
    ["Costa Rica", "CRC"],
    ["Côte d'Ivoire", "CIV"],
    ["Croatia", "CRO"],
    ["Cuba", "CUB"],
    ["Cyprus", "CYP"],
    ["Czech Republic", "CZE"],
    ["Democratic People's Republic of Korea", "PRK"],
    ["Democratic Republic of the Congo", "COD"],
    ["Democratic Republic of Timor-Leste", "TLS"],
    ["Denmark", "DEN"],
    ["Dominican Republic", "DOM"],
    ["Ecuador", "ECU"],
    ["Egypt", "EGY"],
    ["El Salvador", "ESA"],
    ["Eritrea", "ERI"],
    ["Estonia", "EST"],
    ["Ethiopia", "ETH"],
    ["Fiji", "FIJ"],
    ["Finland", "FIN"],
    ["Former Yugoslav Republic of Macedonia", "MKD"],
    ["France", "FRA"],
    ["Gabon", "GAB"],
    ["Gambia", "GAM"],
    ["Georgia", "GEO"],
    ["Germany", "GER"],
    ["Ghana", "GHA"],
    ["Great Britain", "GBR"],
    ["Greece", "GRE"],
    ["Grenada", "GRN"],
    ["Guam", "GUM"],
    ["Guatemala", "GUA"],
    ["Guinea", "GUI"],
    ["Guyana", "GUY"],
    ["Haiti", "HAI"],
    ["Honduras", "HON"],
    ["Hong Kong, China", "HKG"],
    ["Hungary", "HUN"],
    ["India", "IND"],
    ["Indonesia", "INA"],
    ["Iraq", "IRQ"],
    ["Ireland", "IRL"],
    ["Islamic Republic of Iran", "IRI"],
    ["Israel", "ISR"],
    ["Italy", "ITA"],
    ["Jamaica", "JAM"],
    ["Jordan", "JOR"],
    ["Kazakhstan", "KAZ"],
    ["Kenya", "KEN"],
    ["Kuweit", "KUW"],
    ["Kyrgyzstan", "KGZ"],
    ["Lao People's Democratic Republic", "LAO"],
    ["Latvia", "LAT"],
    ["Lebanon", "LIB"],
    ["Lesotho", "LES"],
    ["Liberia", "LBR"],
    ["Libya", "LBA"],
    ["Liechtenstein", "LIE"],
    ["Lithuania", "LTU"],
    ["Luxembourg", "LUX"],
    ["Macao, China", "MAC"],
    ["Madagascar", "MAD"],
    ["Malawi", "MAW"],
    ["Malaysia", "MAS"],
    ["Mali", "MLI"],
    ["Malta", "MLT"],
    ["Mauritius", "MRI"],
    ["Mexico", "MEX"],
    ["Monaco", "MON"],
    ["Mongolia", "MGL"],
    ["Montenegro", "MNE"],
    ["Morocco", "MAR"],
    ["Myanmar", "MYA"],
    ["Namibia", "NAM"],
    ["Nepal", "NEP"],
    ["Netherlands", "NED"],
    ["New Zealand", "NZL"],
    ["Nicaragua", "NCA"],
    ["Niger*", "NIG"],
    ["Nigeria", "NGR"],
    ["Norway", "NOR"],
    ["Oman", "OMA"],
    ["Pakistan", "PAK"],
    ["Panama", "PAN"],
    ["Paraguay", "PAR"],
    ["People's Republic of China ", "CHN"],
    ["Peru", "PER"],
    ["Philippines", "PHI"],
    ["Poland", "POL"],
    ["Portugal", "POR"],
    ["Puerto Rico", "PUR"],
    ["Qatar", "QAT"],
    ["Republic of Korea", "KOR"],
    ["Republic of Moldova", "MDA"],
    ["Romania", "ROU"],
    ["Russian Federation", "RUS"],
    ["Rwanda", "RWA"],
    ["Saint Kitts and Nevis", "SKN"],
    ["Saint Lucia", "LCA"],
    ["Saint Vincent and the Grenadines", "VIN"],
    ["San Marino", "SMR"],
    ["Sao Tome and Principe", "STP"],
    ["Saudi Arabia", "KSA"],
    ["Senegal", "SEN"],
    ["Serbie ", "SRB"],
    ["Seychelles", "SEY"],
    ["Sierra Leone", "SLE"],
    ["Slovakia", "SVK"],
    ["Slovenia", "SLO"],
    ["Somalia", "SOM"],
    ["South Africa", "RSA"],
    ["Spain", "ESP"],
    ["Sri Lanka", "SRI"],
    ["Sudan", "SUD"],
    ["Suriname", "SUR"],
    ["Sweden", "SWE"],
    ["Switzerland", "SUI"],
    ["Syrian Arab Republic", "SYR"],
    ["Thailand", "THA"],
    ["Togo", "TOG"],
    ["Tunisia", "TUN"],
    ["Turkey", "TUR"],
    ["Turkmenistan", "TKM"],
    ["Uganda", "UGA"],
    ["Ukraine", "UKR"],
    ["United Arab Emirates", "UAE"],
    ["United Republic of Tanzania", "TAN"],
    ["United States of America", "USA"],
    ["Uruguay", "URU"],
    ["Uzbekistan", "UZB"],
    ["Vietnam", "VIE"],
    ["Virgin Islands, US ", "ISV"],
    ["Yemen", "YEM"],
    ["Zambia", "ZAM"],
    ["Zimbabwe", "ZIM"] 
  ] unless const_defined?("ISO_COUNTRIES_FOR_SELECT")

  COUNTRIES = Hash[ISO_COUNTRIES_FOR_SELECT].invert unless const_defined?("COUNTRIES")
  COUNTRIES_FOR_SELECT = ISO_COUNTRIES_FOR_SELECT.map { |c|c[0] } unless const_defined?("COUNTRIES_FOR_SELECT")
end
